import { messageKey } from '../../shared/message-key';
export const ERROR_KEYS = {
  VALIDATION_ERROR: messageKey('errors.VALIDATION_ERROR'),
  UNAUTHORIZED: messageKey('errors.UNAUTHORIZED'),
  FORBIDDEN: messageKey('errors.FORBIDDEN'),
  NOT_FOUND: messageKey('errors.NOT_FOUND'),
  CONFLICT: messageKey('errors.CONFLICT'),
  RATE_LIMITED: messageKey('errors.RATE_LIMITED'),
  INTERNAL_ERROR: messageKey('errors.INTERNAL_ERROR'),
  INVALID_CREDENTIALS: messageKey('errors.INVALID_CREDENTIALS'),
  TOO_MANY_ATTEMPTS: messageKey('errors.TOO_MANY_ATTEMPTS'),
  ACCOUNT_SUSPENDED: messageKey('errors.ACCOUNT_SUSPENDED'),
  SESSION_REVOKED: messageKey('errors.SESSION_REVOKED'),
  TOKEN_EXPIRED: messageKey('errors.TOKEN_EXPIRED'),
  TOKEN_ROTATED: messageKey('errors.TOKEN_ROTATED'),
  OTP_INVALID: messageKey('errors.OTP_INVALID'),
  OTP_EXPIRED: messageKey('errors.OTP_EXPIRED'),
  OTP_LOCKED: messageKey('errors.OTP_LOCKED'),
  WEAK_PASSWORD: messageKey('errors.WEAK_PASSWORD'),
  LAST_OWNER: messageKey('errors.LAST_OWNER'),
  NOT_SUPPORTED_YET: messageKey('errors.NOT_SUPPORTED_YET'),
  CSRF_ORIGIN_MISMATCH: messageKey('errors.CSRF_ORIGIN_MISMATCH'),
  INVALID_CURSOR: messageKey('errors.INVALID_CURSOR'),
  INFRASTRUCTURE_UNAVAILABLE: messageKey('errors.INFRASTRUCTURE_UNAVAILABLE'),
} as const;
