export const LINT_PROOF = [
  'export function unused(): number { const unusedLocal = 1; return 0; }',
  "import { Entity } from 'typeorm';",
  "export const leak: any = JSON.parse('{}');",
  'export const unsafe = leak.value;',
  'export function unsafeReturn(): string { return leak; }',
  'export function unsafeCall(): void { leak(); }',
  'export function receives(value: string): number { return value.length; }',
  'export const unsafeArgument = receives(leak);',
  'export function missingReturn() { return 0; }',
  "export function rawError(): never { throw new Error('bad'); }",
  "export function literal(value: string): boolean { return value === 'magic'; }",
  "export function cases(value: string): void { switch (value) { case 'magic': break; } }",
  'export function floating(): void { Promise.resolve(); }',
  'export function logged(): void { console.log(Entity); }',
  'export function magic(value: number): number { return value + 42; }',
  'export class Unnecessary { public static value = 1; }',
  'export function cycle(): unknown { return forwardRef(() => Unnecessary); }',
  'export function lengthy(value: number): number {',
  ...Array.from({ length: 305 }, () => 'value += 1;'),
  'return value;',
  '}',
  'export function complex(value: number): number {',
  ...Array.from({ length: 12 }, (_, index) => `if (value === ${String(index)}) { value += 1; }`),
  'return value;',
  '}',
].join('\n');
export const EXPECTED_LINT_RULES = [
  '@typescript-eslint/no-unused-vars',
  'no-console',
  'max-lines',
  'max-lines-per-function',
  'complexity',
  '@typescript-eslint/explicit-function-return-type',
  '@typescript-eslint/no-magic-numbers',
  '@typescript-eslint/no-extraneous-class',
  '@typescript-eslint/no-explicit-any',
  '@typescript-eslint/no-unsafe-assignment',
  '@typescript-eslint/no-unsafe-member-access',
  '@typescript-eslint/no-unsafe-call',
  '@typescript-eslint/no-unsafe-return',
  '@typescript-eslint/no-unsafe-argument',
  '@typescript-eslint/no-floating-promises',
  'no-restricted-syntax',
  'no-restricted-imports',
];
